ndv6/core-ios

- OLCore/Classes/Utilities/FormValidation/Rules/MinValueRule.swift
Failed when validating currency.
Extract the digits.
> Fix: Min Value Rule Validation

- Example/Podfile.lock
- OLCore.podspec
- OLCore/Classes/Utilities/FormValidation/Rules/MinValueRule.swift
**Release Notes:**
- Fix minimum value of currency validation.
> Release 0.1.1

- OLCore/Classes/Constants/RegexString.swift
- OLCore/Classes/Utilities/FormValidation/Rules/FullNameRule.swift
https://ndv666.atlassian.net/browse/CN1-753
Incorrect regex format.
> Fix(Validation): [CN1-754] Person Name Validation

- OLCore/Classes/Constants/Separator.swift
- OLCore/Classes/Extensions/Double+Extension.swift
- OLCore/Classes/Extensions/FormTableViewController+TextField.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MaxDoubleRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MaxIntegerRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MinDoubleRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MinIntegerRule.swift
- OLCore/Classes/Views/Button/Styles/DefaultButtonStyle.swift
- OLCore/Classes/Views/TextArea/TextArea.swift
- OLCore/Classes/Views/TextField/TextField.swift
- OLCore/Classes/Views/TextField/Types/AmountInputType.swift
- OLCore/Classes/Views/TextField/Types/DatePickerInputType.swift
- OLCore/Classes/Views/TextField/Types/DecimalInputType.swift
- OLCore/Classes/Views/TextField/Types/DropDownInputType.swift
- OLCore/Classes/Views/TextField/Types/FreeTextInputType.swift
- OLCore/Classes/Views/TextField/Types/InputType.swift
- OLCore/Classes/Views/TextField/Types/PickerInputType.swift
- https://ndv666.atlassian.net/browse/CN1-859
- https://ndv666.atlassian.net/browse/CN1-861
- https://ndv666.atlassian.net/browse/CN1-868
- https://ndv666.atlassian.net/browse/CN1-864
- Textarea styling
- Integer and Double rule validation
- Create `DecimalInputType`,
- Differentiate between Integer and Double rule validation,
> Fix(Validation): Textarea and Validation

- OLCore/Classes/Constants/AccessibilityIdentifier.swift
- OLCore/Classes/Constants/Separator.swift
- OLCore/Classes/Extensions/String+Extension.swift
- OLCore/Classes/Views/Button/Button.swift
- OLCore/Classes/Views/RadioButton/RadioButton.swift
- OLCore/Classes/Views/TextField/TextField.swift
https://ndv666.atlassian.net/browse/CN1-895
Accessibility Identifier:
- Textfield
- Textarea
- Button with Title
- Radio Button
Set Accessibility Identifier when the name or title changed.
None.
None.
None.
None
> Chore(AccessibilityId): [CN1-895] Basic Accessibility Identifier

- .gitignore
- OLCore/Classes/Models/Option.swift
- OLCore/Classes/ViewControllers/DropDownViewController/DropDownItemCell.swift
- OLCore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
Enhance dropdown to have Main Label and Description Label
> Chore(DropDown): Enhance dropdown to have Main Label and Description Label

- OLCore/Classes/Constants/Separator.swift
- OLCore/Classes/Extensions/Double+Extension.swift
- OLCore/Classes/Extensions/String+Extension.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MaxDoubleRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/MinDoubleRule.swift
- OLCore/Classes/Views/TextField/Types/DecimalInputType.swift
https://ndv666.atlassian.net/browse/CN1-925
Decimal separator across localization.
Accept `.` and `,`
> Fix(Input): Decimal Separator

- OLCore/Classes/Utilities/FormValidation/Rules/RequiredRule.swift
- OLCore/Classes/Views/SectionCollection/SectionCollection.swift
https://ndv666.atlassian.net/browse/CN1-935
- Required Rule: should reject whitespace.
- Create some new empty cell.
None.
None.
None.
None.
None
> Fix(Validation): Required Rule should reject whitespace

- OLCore/Classes/Constants/DefaultValue.swift
- OLCore/Classes/Extensions/Float+Extension.swift
- OLCore/Classes/Extensions/String+Extension.swift
- OLCore/Classes/ViewControllers/TableViewController/FormTableViewController.swift
- OLCore/Classes/Views/TextField/Types/DecimalInputType.swift
> Fix Float Value

- OLCore/Classes/Constants/DefaultValue.swift
add new empty value in constant EmptyCGFloat
> add CGFloat default empty value

- OLCore/Classes/Coordinators/Coordinator.swift
> Create Base Coordinator

- OLCore/Classes/ViewControllers/ImagePickerViewController/ImagePicker.swift
- OLCore/Classes/Views/ImageSelectionInput/ImageSelectionInput.swift
- OLCore/Classes/Views/TableView/ImageInputTableViewCell.swift
create image input component from Button class
> Feature(PropertyPhoto): image input component

- OLCore/Classes/Constants/DateFormat.swift
- OLCore/Classes/Extensions/Date+Extension.swift
For monthly "Ditagih Setiap Tanggal"
> add formatInDay support

- OLCore/Classes/ViewControllers/ImagePickerViewController/ImagePicker.swift
- OLCore/Classes/Views/TableView/ImageInputTableViewCell.swift
bug fix for ticket https://ndv666.atlassian.net/browse/CN1-1181
> update imagepicker component

- OLCore.podspec
- OLCore/Classes/Extensions/Collection+Extension.swift
- OLCore/Classes/Extensions/Date+Extension.swift
- OLCore/Classes/Extensions/Double+Extension.swift
- OLCore/Classes/Extensions/Formatter+Extension.swift
- OLCore/Classes/Extensions/Int+Extension.swift
- OLCore/Classes/Extensions/String+Extension.swift
- OLCore/Classes/Extensions/UIImage+Extension.swift
- OLCore/Classes/Extensions/UINavigation+ControllerExtension.swift
- OLCore/Classes/Extensions/UITabBarController+Extension.swift
- OLCore/Classes/Extensions/UITableViewCell+Extension.swift
- OLCore/Classes/Extensions/UIView+Extension.swift
Hotfix from `rc-0.2.0` into `develop` branch.
> Hotfix from rc-0.2.0

- OLCore/Classes/Views/CompletionInput/CompletionInput.swift
- OLCore/Classes/Views/TableView/CompletionInputTableViewCell.swift
add completion input component
> add completion input

- OLCore/Classes/Extensions/UIView+Extension.swift
add method to manually add border to single side of the rectangle
> add new method to add border in uiview extension

- OLCore/Classes/Extensions/Double+Extension.swift
- OLCore/Classes/Views/TextField/Types/DecimalInputType.swift
> Fix(Extension): Decimal Cleanup Formula

- OLCore/Classes/Constants/DefaultValue.swift
- OLCore/Classes/Models/Option.swift
Add value in option model to support option that must return multiple Id
> Core: Enchance Option

- Example/OLCore.xcodeproj/project.pbxproj
- Example/OLCore.xcodeproj/xcshareddata/xcschemes/OLCore-Example.xcscheme
- Example/Podfile.lock
- OLCore/Classes/Extensions/Array+Extension.swift
- OLCore/Classes/ViewControllers/ImagePickerViewController/ImagePicker.swift
- OLCore/Classes/Views/SelectionInput/SelectionInputItemCell.swift
- README.md
- docs/pull_request_template.md
- We need deployment guide so anyone can deploy this library.
- Fix pod lib lint warning.
> Chore(Guide): Deployment Guide

- OLCore/Classes/Extensions/Double+Extension.swift
None.
None.
None.
None.
None.
None.
> Chore(Finance): add minus currency format

- OLCore.podspec
None.
None.
None.
None.
None.
None.
> bump version from 0.4.0 to 0.5.0

- OLCore/Classes/Extensions/UIImage+Extension.swift
https://ndv666.atlassian.net/browse/CN1-1432
Issue with iOS photo orientation that did not send orientation
Use fix orientation function
None.
None.
None.
None.
> Bug(sprint 20): Foto KTP Terbalik

- OLCore/Classes/Extensions/UIView+Extension.swift
- OLCore/Classes/Views/View/View.swift
None.
- How to use Gradient as a background color.
- How to create drop shadow with corner radius.
- Create `gradientLayer` property and `setGradientColors` method in `View` class.
- Create `shadowLayer` property and `setDropShadow` method in `View` class.
**Note:** There is a limitation, you can not use gradient and drop shadow at the same time.
None.
None.
None.
None
> Feature: Gradient Layer

- docs/pull_request_template.md
None.
There are PR sequence dependencies that reviewer can't identify.
Create `Dependencies` section in PR Template.
None.
None.
None.
None.
None
> Update PR Template

- OLCore.podspec
None.
Bump version from `0.5.0` to `0.6.0`
None.
None.
None.
None.
None.
> Bump version from 0.5.0 to 0.6.0

- OLCore/Classes/Views/NestedTableView/NestedTableViewConnector.swift
- OLCore/Classes/Views/NestedTableView/NestedTableViewContainer.swift
None.
There is no layout that supports adaptive footer button.
Utilize `NestedTableView` with minimum height.
None.
None.
None.
None.
> Chore: Stretch Nested Tableview

- OLCore.podspec
None.
None.
None.
None.
None.
None.
None.
> bump version from 0.6.0 to 0.6.1

- OLCore/Classes/Views/Button/Button.swift
- OLCore/Classes/Views/Button/Styles/ButtonStyle.swift
- OLCore/Classes/Views/Button/Styles/DefaultButtonStyle.swift
- OLCore/Classes/Views/View/View.swift
None.
Gradient and Shadow does not work properly in dynamic view size.
Override `draw` method.
https://stackoverflow.com/questions/39572990/applying-gradient-background-for-uiview-using-auto-layout
None.
None.
None.
> Fix: Gradient and Shadow in Dynamic View Size

- OLCore.podspec
Fix Gradient and Shadow in Dynamic Layout.
> Bump Version 0.6.1 to 0.6.2

- OLCore/Classes/Views/Button/Button.swift
- OLCore/Classes/Views/View/View.swift
- README.md
None.
Button title goes to invisible in gradient mode.
Insert the gradient layer at `0` index.
None.
None.
None.
None.
> Fix: Button Title in Gradient Mode

- Example/OLCore.xcodeproj/project.pbxproj
- Example/Podfile.lock
- OLCore/Classes/Constants/LayoutPosition.swift
- OLCore/Classes/ViewControllers/SelectionInputViewController/SelectionInputViewController.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
- OLCore/Classes/Views/Button/Button.swift
None.
Can not render close button on the right side.
Replace `closeButtonEnabled` with `closeButtonPosition`
None.
None.
None.
None.
> Feature: Customize Close Button Position

- OLCore.podspec
Bump version from 0.6.3 to 0.6.4
> Bump version from 0.6.3 to 0.6.4

- OLCore/Classes/ViewControllers/DropDownViewController/DropDownItemCell.swift
- OLCore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
- OLCore/Classes/Views/Button/Button.swift
- OLCore/Classes/Views/TextField/Types/DropDownInputType.swift
None.
1. Update DropDownVC and DropDownCellItem component, add new method for rendering custom text
2. update component ``Button.swift`` so now it accept custom color for highlighted text
None.
None.
None.
None.
None.
> update dropdown main component

- OLCore/Classes/Constants/FieldBorderStyle.swift
- OLCore/Classes/Constants/RegexString.swift
- OLCore/Classes/Constants/TextFieldBorderStyle.swift
- OLCore/Classes/Extensions/FormTableViewController+RadioButton.swift
- OLCore/Classes/Extensions/FormTableViewController+SelectionInput.swift
- OLCore/Classes/Extensions/FormTableViewController+TextField.swift
- OLCore/Classes/Extensions/FormTableViewController+UITextField.swift
- OLCore/Classes/Extensions/FormTableViewController+UITextView.swift
- OLCore/Classes/Extensions/TextArea+Border.swift
- OLCore/Classes/Extensions/TextField+Border.swift
- OLCore/Classes/Extensions/UITableView+Extension.swift
- OLCore/Classes/Utilities/FormValidation/InputProtocol.swift
- OLCore/Classes/Utilities/FormValidation/InputValidator.swift
- OLCore/Classes/Utilities/FormValidation/Rules/EmailRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/PasswordRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/PersonNameRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/PhoneRule.swift
- OLCore/Classes/ViewControllers/TableViewController/FormTableViewController.swift
- OLCore/Classes/ViewControllers/TableViewController/TableViewController.swift
- OLCore/Classes/Views/Button/Button.swift
- OLCore/Classes/Views/CompletionInput/CompletionInput.swift
- OLCore/Classes/Views/ImageSelectionInput/ImageSelectionInput.swift
- OLCore/Classes/Views/NestedTableView/NestedTableViewContainer.swift
- OLCore/Classes/Views/RadioButton/RadioButton.swift
- OLCore/Classes/Views/SelectionInput/SelectionInput.swift
- OLCore/Classes/Views/TableView/TableView.swift
- OLCore/Classes/Views/TextArea/TextArea.swift
- OLCore/Classes/Views/TextField/TextField.swift
- OLCore/Classes/Views/TextField/TextFieldStyle.swift
None.
- Textfield bottom-line style.
- Return Key as a Next button action to be able to move to the next textfield.
- Create Email Validation.
- Create custom tableview `reloadData` to support nested tableview.
- Fix refresh error validation message.
- Fix `gradientLayer` order.
- Rename `FullNameRule` into `PersonNameRule`.
None.
None.
None.
None.
None.
> Feature(TextField): Support Bottom Line Style

- OLCore.podspec
Bump version from 0.6.4 to 0.6.5
> bump version from 0.6.4 to 0.6.5

- OLCore/Classes/Constants/CoreStyle.swift
- OLCore/Classes/Extensions/TextField+Border.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
- OLCore/Classes/Views/TextField/TextField.swift
None.
None.
None.
None.
None.
None.
None.
> Chore(NavigationTitle): change navigation text color

- OLCore/Classes/Extensions/UIView+Extension.swift
- OLCore/Classes/Helpers/NavigationHelper.swift
- OLCore/Classes/Utilities/FormValidation/InputValidator.swift
- OLCore/Classes/ViewControllers/DropDownViewController/DropDownItemCell.swift
- OLCore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
- OLCore/Classes/ViewControllers/SelectionInputViewController/SelectionInputViewController.swift
- OLCore/Classes/ViewControllers/TableViewController/FormTableViewController.swift
- OLCore/Classes/ViewControllers/TableViewController/TableViewController.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
- OLCore/Classes/Views/Button/Styles/ButtonStyle.swift
- OLCore/Classes/Views/Button/Styles/DefaultButtonStyle.swift
- OLCore/Classes/Views/NestedTableView/NestedTableView.swift
- OLCore/Classes/Views/NestedTableView/NestedTableViewConnector.swift
- OLCore/Classes/Views/SectionCollection/SectionCollection.swift
- OLCore/Classes/Views/TableView/TableView.swift
- OLCore/Classes/Views/TableView/TableViewSection.swift
- OLCore/Classes/Views/TextField/TextField.swift
- OLCore/Classes/Views/TextField/Types/DropDownInputType.swift
None.
- Create Dropdown with search feature.
- replace `appendSection(section: TableViewSection)` with `appendSection(_ section: TableViewSection)`.
- Create `openAppSetting` method.
- Make TableView inset to be customable.
- Fix Error Message behavior.
- New attribute `imageRenderingMode` in `ButtonStyle`, Koalakos and eLiving should be:
```var imageRenderingMode = UIImage.RenderingMode.alwaysTemplate```
None.
None.
None.
None.
None.
> Feature: Dropdown with Search

- OLCore/Classes/Constants/DateFormat.swift
- OLCore/Classes/Extensions/Date+Extension.swift
- OLCore/Classes/Views/PickerView/MonthYearPickerView.swift
- OLCore/Classes/Views/PickerView/Styles/DatePickerViewStyle.swift
- OLCore/Classes/Views/PickerView/Styles/DefaultDatePickerStyle.swift
- OLCore/Classes/Views/TextField/Types/InputType.swift
- OLCore/Classes/Views/TextField/Types/MonthYearPickerInputType.swift
https://ndv666.atlassian.net/browse/CN1-1611
https://ndv666.atlassian.net/browse/CN1-1612
iOS did not have Month Year Picker View
- Create Month Year Picker View with `inputType` protocol
- Add `monthWithYear` date format
- Add `DatePickerViewStyle`
None.
None.
None.
None.
> Feature: month year picker view

- OLCore.podspec
- Create Month Year Picker View with inputType protocol
- Add monthWithYear date format
- Add DatePickerViewStyle
> bump version from 0.7.0 to 0.8.0

- OLCore/Classes/Constants/RegexString.swift
- OLCore/Classes/Utilities/FormValidation/Rules/IndonesianPhoneRule.swift
- OLCore/Classes/Utilities/FormValidation/Rules/InternationalPhoneRule.swift
- OLCore/Classes/ViewControllers/ImagePickerViewController/ImagePicker.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
None.
- Rename Phone rule to Indonesia phone Rule
- Create InternationalPhoneRule
- change shadow for navigationbar
None.
None.
None.
None.
None.
> Chore new phone rule and navigation bar shadow color

- OLCore/Classes/Views/Button/Button.swift
None.
- Gradient in button overlap button image
- Bring image to front
None.
None.
None.
None.
> Chore: imageview in button always in front

- OLCore/Classes/Extensions/UIImageView+Extension.swift
- OLCore/Classes/ViewControllers/TableViewController/TableViewController.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
None.
need to set image background and resize to specific size
None.
None.
None.
None.
None.
> Feature: function for set image from url

- OLCore/Classes/Views/Button/Button.swift
None.
- setupConstraint looping that caused by `bringtofront` func for imageView inside button
- Remove imageView's `bringtofront`
None.
None.
None.
None.
> Fix: setupConstraint looping

- OLCore.podspec
bump version from 0.8.0 to 0.9.0
> bump version from 0.8.0 to 0.9.0

- OLCore/Classes/ViewControllers/PageView/PageViewController.swift
- OLCore/Classes/ViewControllers/PageView/PageViewWithVC.swift
None.
None.
None.
None.
None.
None.
None.
> add page view controller

- OLCore/Classes/ViewControllers/PageView/PageViewController.swift
None.
None.
None.
None.
None.
None.
None.
> Add Activity And Page Control PageViewControlloer

- OLCore/Classes/ViewControllers/PageView/PageViewController.swift
None.
- There is constraint conflicts showing in the logs
- Pagecontrol setup still in the core
-  Commented Constraint Conflicts in empty cell (Need to check in another cient application)
-  Move pagecontrol setup to the client
None.
None.
None.
None.
> update pageview and remove error constraint

- OLCore/Classes/Extensions/UIImage+Crop.swift
- OLCore/Classes/ViewControllers/CameraViewController/CameraViewController+Gallery.swift
- OLCore/Classes/ViewControllers/CameraViewController/CameraViewController.swift
- OLCore/Classes/ViewControllers/CameraViewController/CameraViewControllerDelegate.swift
Camera Delegate should send original image and cropped image.
> Chore: Enhance Camera Delegate

- OLCore/Classes/Extensions/String+Format.swift
Create string prefix with number of length.
> Chore: Fetch String Prefix

- OLCore/Classes/Models/EventCalendar.swift
- OLCore/Classes/Utilities/CalendarUtil/CalendarSync.swift
- OLCore/Classes/Utilities/New Group/CalendarSync.swift
Add Sync Event To Calendar
None.
None.
None.
None.
None.
> Add Sync To Calendar

- OLCore/Classes/Extensions/UIImage+Compression.swift
None.
Resize image base on a specific width.
Create method as a UIImage extension.
None.
None.
None.
None.
> Feature: Resize Image

- OLCore/Classes/Constants/CoreStyle.swift
- OLCore/Classes/Extensions/UIColor+Extension.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
None.
navbar separator color affect different apps
None.
None.
None.
None.
None.
> Bug(NavigationBar): move function to UIColor extension, use corestyle

- OLCore/Classes/Utilities/FormValidation/Rules/Rule.swift
None.
Client can not create custom rule due to private `status`.
Make `status` as a `public`.
None.
None.
None.
None.
> fix rule access level

- OLCore/Classes/Extensions/Data+DebugTools.swift
- OLCore/Classes/Extensions/String+DebugTools.swift
None.
It's hard to debug the JSON string format.
Create pretty print as a `String` and `Data` extension.
None.
None.
None.
None.
> json debug tools

- OLCore/Classes/ViewControllers/PreviewFileViewController/PreviewFile.swift
None.
None.
Add UIDocumentInteraction to preview file.
None.
None.
None.
None.
> Feature(sprint 25): Document interaction

- OLCore/Classes/Views/TextField/Types/MonthYearPickerInputType.swift
None.
Formate date on date picker didn't change even after changing the language
Set locale when init the picker view
None.
None.
None.
None.
> Fix locale

- OLCore/Classes/ViewControllers/NavigationController/TabBarNavigationController.swift
- OLCore/Classes/ViewControllers/ViewController/ViewController.swift
None.
Cannot passed data when programatically changed tab
return moveTabBarToController vc value. With this enhancement, we can control/passed value while moving to the other tab.
None.
None.
None.
None.
> chore: return moveTabBarToController value

- OLCore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
- OLCore/Classes/ViewControllers/DropDownViewController/EmptyItemCell.swift
None.
- When options is empty, app only show blank page
- Add emptyTitleCell
None.
None.
None.
None.
> Feature: add empty state for dropdown

- OLCore/Classes/Constants/CharacterSets.swift
- OLCore/Classes/Extensions/FormTableViewController+UITextField.swift
- OLCore/Classes/Extensions/String+Format.swift
- OLCore/Classes/ViewControllers/PageView/PageViewController.swift
- OLCore/Classes/Views/TextField/TextField.swift
None.
TextField should be able to reject unnecessary characters.
- Create `CharacterSets` constant.
- Create new property `allowedCharacters` in `TextField` class.
- Create `filterAllowedCharacters` method as a string extension.
None.
None.
None.
None.
> Feature: Allowed Characters

- OLCore.podspec
bump version from 0.11.0 to 0.12.0
> bump version from 0.11.0 to 0.12.0

- OLCore/Classes/ViewControllers/DropDownViewController/DropDownViewController.swift
None.
Glitch on Dropdown Search TextField.
Onetime create search textfield.
None.
None.
None.
None.
> Fix: Glitch on Dropdown Search TextField

- OLCore.podspec
None.
None.
None.
None.
None.
None.
None.
> bump version from 0.12.0 to 0.13.0

- OLCore/Classes/Extensions/UIView+Extension.swift
None.
Need rotate loading image
None.
None.
None.
None.
None.
> Feature: Rotate infinite uiview
